name: Trigger auto deployment for fin-auto-push

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fin-auto-push-AutoDeployTrigger-6809a322-a33f-4a08-b39c-d68ddc7a0cf5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FINAUTOPUSH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FINAUTOPUSH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FINAUTOPUSH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.FINAUTOPUSH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINAUTOPUSH_REGISTRY_PASSWORD }}
          containerAppName: fin-auto-push
          resourceGroup: fin-auto-push-rg
          imageToBuild: leimai/fin-auto-push:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


